language: scala
scala: 2.11.7
jdk: oraclejdk8
before_script: ulimit -u 30000
install: gradle check
script: gradle test jar
notifications:
  slack: datamountaineers:gpg5e7VabFjAT1gQZqwxgsqP
after_success:
  - bash <(curl -s https://codecov.io/bash)

